---
- name: Install dependencies
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Grafana APT key
  shell: wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add Grafana repository
  shell: echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
