---
- name: Install required packages
  apt:
    name:
      - prometheus
      - prometheus-node-exporter
      - prometheus-alertmanager
    state: present
    update_cache: yes

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Enable and start Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started
